import Navigation from "@/components/navigation"; // @ => src klasörüne denk gelir.
import "./globals.css";
import { Container } from "@mui/material";

// sitenin titleını buradan ayarlarız. her sayfada aynı title görünmemesini istersek diğer sayfalarda metadata propunu ezebiliriz.
// title altındaki default genel olarak gelir. diğer pagelerden ezersek %s yer tutucusuna değer veririz.
export const metadata = {
  title: { template: "%s / Next Blog App", default: "Welcome /Next Blog App" },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigation />
        </header>
        <main>
          <Container sx={{ my: 3 }}>{children}</Container>
        </main>
      </body>
    </html>
  );
}
